### ISSUE TITLE
"Alfresco is running without Share Services..." message with Kerberos SSO

### ISSUE THREAD

**Issue by loftux** [loftuxab/share-community-loftux#6]
This is a cross reference to https://issues.alfresco.com/jira/browse/ALF-21776

Since there is no easy way to reproduce, the message will just be hidden for now. A sysadmin will now if they have share services installed or not.

**Comment by loftux** [comment]
Alfresco seems to have no interest in resolving this issue. The fix that we did here work, so let's go with this.

**Comment by yregaieg** [comment]
@loftux 
IMHO, an extension to the header with this snippet in the controller would be a better temporary fix. As it ensure easier upgrades and does not override anything.

```js
var shareServicesWarning = widgetUtils.findObject(model.jsonModel, "id", "HEADER_SHARE_SERVICES_WARNING");
if (shareServicesWarning != null) {
    shareServicesWarning.config.shareServices = {
        nocheck:true
    };
}
```

**Comment by derekhulley** [comment]
See https://issues.alfresco.com/jira/browse/SHA-2120.
A pull request against SHA-2120 would be great.

**Comment by yregaieg** [comment]
@derekhulley I do not think we are talking about the same issue here, I think the problem @loftux and I were having is due to the SSO not working for the particular request made to the repo to check for the version (not sure if it is a filter problem or a url construction problem against the wrong surf proxy) in any case in my case at least, the access logs from tomcat was showing a 401 status message whenever share tries to get information about the availability of share services.... And ower fix was to simply skip that check everytime and make sure that Share services are on board !
